#!/usr/local/bin/python

from subprocess import call
from sys import path
import os
path.append("/usr/local/share/networkmgr")
from trayicon import trayIcon

if os.path.exists("/usr/local/bin/netcardmgr"):
    call("doas netcardmgr",
         shell=True)

i = trayIcon()
i.tray()
