#!/usr/bin/env python3.6

from sys import path
import signal
path.append("/usr/local/share/networkmgr")
from trayicon import trayIcon

signal.signal(signal.SIGINT, signal.SIG_DFL)

i = trayIcon()
i.tray()
